### ISSUE TITLE
Android 8+: "Write Settings" unreliable

### ISSUE THREAD

**Issue by RipperDrone** [ImmersionRC/LapRFTimingAndroidPublic#1]
Pressing "Write Settings" doesn't work most of the time, have to press several times before it works. Seems the connection protocol (serial over BT?) has unstable timings...?

**Comment by tonycake** [comment]
I have heard a few reports of this, but have never been able to reproduce it. 

From a code point of view, the function responsible for writing settings to the device is sendToDevice() in SetupActivity.java. 

Before it starts, it clears the checkbox beside the WRITE SETTINGS button, which is then checked when the settings are read from the device in receivedRFSettings(). 

It is true that the read settings are never compared with those written, which might be a wise thing to do...

When write settings fails, is the checkbox checked after writing?

**Comment by tonycake** [comment]
Ok, bit more poking around, I did manage to get a Samsung phone to fail to write about once in every 10 or so tries. 

Looking at the log it seems that the settings are being sent, but not received to confirm. 

Upon success, the debug console looks like this: 
D/BluetoothBackground: sendMultiChannelSettings
D/BluetoothBackground: Characteristic wrote
D/BluetoothBackground: SendBytes to devices
D/BluetoothBackground: writeMessage: 0 -> 20
    writeMessage: 20 -> 40
D/BluetoothBackground: writeMessage: 40 -> 60
    writeMessage: 60 -> 80
    writeMessage: 80 -> 100
D/BluetoothBackground: writeMessage: 100 -> 120
    writeMessage: 120 -> 140
    writeMessage: 140 -> 160
    writeMessage: 160 -> 180
D/BluetoothBackground: writeMessage: 180 -> 200
    writeMessage: 200 -> 220
    writeMessage: 220 -> 240
D/BluetoothBackground: writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
    writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
D/BluetoothBackground: writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
    writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
D/BluetoothBackground: writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
    writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
D/BluetoothBackground: writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
    writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
D/BluetoothBackground: writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
D/BluetoothBackground: writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
    writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
    writeMessageFromQueue: 20 bytes
D/BluetoothBackground: Characteristic wrote
**D/protocolDecoder: receive RF settings**    **<- First of 8 reads**
D/protocolDecoder: receive RF settings
D/protocolDecoder: receive RF settings
D/protocolDecoder: receive RF settings
D/protocolDecoder: receive RF settings
D/BluetoothGatt: readRssi() - device: 94:54:93:14:6A:XX
D/protocolDecoder: receive RF settings
D/protocolDecoder: receive RF settings
D/protocolDecoder: receive RF settings

And on failure: 

D/BluetoothBackground: **sendMultiChannelSettings**
D/BluetoothBackground: SendBytes to devices
    writeMessage: 0 -> 20
D/BluetoothBackground: writeMessage: 20 -> 40
    writeMessage: 40 -> 60
D/BluetoothBackground: writeMessage: 60 -> 80
    writeMessage: 80 -> 100
    writeMessage: 100 -> 120
D/BluetoothBackground: writeMessage: 120 -> 140
    writeMessage: 140 -> 160
    writeMessage: 160 -> 180
    writeMessage: 180 -> 200
D/BluetoothBackground: writeMessage: 200 -> 220
    writeMessage: 220 -> 240
    writeMessageFromQueue: 20 bytes
D/BluetoothGatt: readRssi() - device: 94:54:93:14:6A:XX
D/BluetoothBackground: Characteristic wrote
    writeMessageFromQueue: 20 bytes

Note the lack of receiving settings...

**Comment by RipperDrone** [comment]
> When write settings fails, is the checkbox checked after writing?

@anthonycake no, it only acknowledges a **successful** write with the checkbox icon checked :-)

**Comment by RipperDrone** [comment]
Getting a feeling that changing several edit values simultaneously and then trying to save makes the write failure more likely - can it be about data traffic / high load somehow?

**Comment by tonycake** [comment]
Ok, spent a few hours debugging... no closer to a solution. On my devices the problem is rare, but it does occur every 10-20 writes. 
The data is correctly written to the low level BT layer (GATT), but for some reason isn't received by the LapRF.

**Comment by RipperDrone** [comment]
Is there options to set different baud rates like in true serial protocols? Maybe slower is more reliable?

**Comment by RipperDrone** [comment]
Statistics from my last attempts on LG V30: 2 out of 10 write attempts are successful, balance 8 are failing

**Comment by RipperDrone** [comment]
For some reason very first few times it mostly writes ok. On subsequent attempts it seems to get worse from some point. Looks like some fractions of the data stream get stuck in a buffer or fragmented on LapRF receive buffer side, so it keeps waiting for balance correct data. Maybe flushing receive buffer after a certain timeout period could be a workaround. Is something like flushing buffers doable in high level data transfer functions or does this dig deep into low level BT protocol handling so it is out of your reach? :-/

**Comment by tonycake** [comment]
Ok, I just pushed a change that seems to increase reliability quite a bit. Root cause of the problem still not understood, but this should work for now. 
RipperDrone, can you test it?

**Comment by RipperDrone** [comment]
@anthonycake - trying to test: Since I am an Android build environment noob, here is how far I got: 
![image](https://user-images.githubusercontent.com/12601105/63967441-b82ace00-ca9d-11e9-8681-f10ecde0664f.png)

**Comment by RipperDrone** [comment]
What I did: 
- install Android Studio Win x64
- Download master .zip from Github
- extract to path 
- open project in Android studio, point to path
- let Android studio try to build

Pls give me a pointer what I am doing wrong here... :-)

**Comment by RipperDrone** [comment]
![image](https://user-images.githubusercontent.com/12601105/63969853-18703e80-caa3-11e9-8487-981f2acd5aee.png)

seems stuck in the build process, status message says NDK version unknown...?

**Comment by bshurn** [comment]
I have a 100% repro on a Pixel 3 XL without the fix. 

I was unable to build (no Android dev experience). I did what RipperDrone did except I cloned the repo and I tried to both open and import the project to Android studio.

Fwiw I am able to build and debug the boilerplate project templates. 

Could you share the APK?

**Comment by Nandox7** [comment]
Make sure you sync first before building, so that it downloads the version specific files.

**Comment by RipperDrone** [comment]
@Nandox7 That's what it automatically does when opening the project for the first time. Sync'ing takes some 1-2 minutes, and it completes without any warning. Still the build process doesn't work and cancels with a warning (see my former comments)

**Comment by RipperDrone** [comment]
sync process gets stuck here... 
![image](https://user-images.githubusercontent.com/12601105/64083101-ddc40b80-cd19-11e9-8b6b-755271fe33e3.png)

**Comment by RipperDrone** [comment]
![image](https://user-images.githubusercontent.com/12601105/64083107-0cda7d00-cd1a-11e9-87a9-66c821601b46.png)

**Comment by RipperDrone** [comment]
@anthonycake - can you pls help me with some hints how to get the latest source compiled? Still no success... :-(

**Comment by RipperDrone** [comment]
@anthonycake @Nandox7 pretty please: How can we compile / test your commits? Doesn't work on my Windows 10 / Android Studio... :-/

**Comment by Nandox7** [comment]
I'll check later when at home and report, don't have access to a Win10 machine at the moment,

**Comment by Nandox7** [comment]
Ok, so in windows I go the same errors.
I did not went one by one fixing them to check but the following fixed it.
1. Install NDK to get rid of the NDK unknow error: File > Project Strucuture > SDK Location - Install NDK
2. Change SDK versions: File > Project Structure > Modules > app - Change "Compile Sdk version" and "Build tools" to latest. Should be API 29 and 29.0.x

As you press apply it should do the sync again and this time without the NPE and finishing.

**Comment by RipperDrone** [comment]
@Nandox7 - thank you, it now completed the sync and then ran the 'Build': 

![image](https://user-images.githubusercontent.com/12601105/65066185-33d4b800-d984-11e9-8f0e-0b3192770237.png)

I can get to an output file in this folder now:
![image](https://user-images.githubusercontent.com/12601105/65066221-44852e00-d984-11e9-9712-eb9e6fddcfaa.png)

However, this cannot be installed on the tablet, even after overriding PlayProtect it won't install.

Could you pls help me in:
- generating a release file instead of debug (I hit error messages when changing the version to release)
- getting an .apk output that I can install on Android devices without errors?

**Comment by RipperDrone** [comment]
Error shown in release build type:

![image](https://user-images.githubusercontent.com/12601105/65066476-b52c4a80-d984-11e9-8511-5ce4da44910a.png)

**Comment by RipperDrone** [comment]
_sigh_, was just looking at easily creating an .apk file to test... :-(

**Comment by Nandox7** [comment]
To create a release version the app/apk needs to be signed with a certificate. 
You always need to create your own (ImmersionRC would not share theirs. :)) but is a easy process 
That's why you see the jks error, Android Studio can't find file that keeps the certificate.

To create one follow these steps: https://developer.android.com/studio/publish/app-signing#generate-key

Not that big of an issue as you doing this apk for your owb use but never loose the certificate for an app published on the Play Store. :)

**Comment by RipperDrone** [comment]
@Nandox7 Thank you, got it. To work around this more or less tedious release process, how can I install the debug version onto my phone? It will pop an error message 'cannot install'... 😬

**Comment by RipperDrone** [comment]
Maybe best idea to facilitate testing for non-coders: Can there be test .apk's auto-created by travis or some scripted build platforms? I would love to contribute by testing, though the barrier seems to be quite high for people like me to create an a.pk from the source code...

**Comment by Nandox7** [comment]
Easiest way is to connect the phone to the computer and enable the developer/debug mode.

The issue with APK is not exactly the file itself is the Android system. You need to enable the option to allow install unknown apps.

Travis would do, but given the flow of PR's at the moment there is not much new stuff to build.

**Comment by RipperDrone** [comment]
@Nandox7 Have tried Android 8 and (update came OTA) Andriod 9 on my Galaxy S3 Tab: Activated Developer Options, then allowed to install unknown apps. Still the compiled debug .apk ended with 'has not been installed' (after asking whether even without certificate I would like to install --> install anayway). Could you do us a favour and provide a compiled .apk so we can test, please?

**Comment by Nandox7** [comment]
I can sure.
In the mean time make sure you don't have any version installed or it will conflict and cause that.

**Comment by RipperDrone** [comment]
@Nandox7 Installed apps double-checked on my tablet - no previously installed version. Seems it doesn't want to install my compiled debug version for different reasons. Developer mode is active... :-/

**Comment by RipperDrone** [comment]
@Nandox7 @anthonycake pls create an .apk version as release version so we can test. The tool chain seems to be over my head, doesn't work (see previous comments), unable to compile a release version myself or to install a debug version on my talet for testing... :-(

**Comment by RipperDrone** [comment]
![image](https://user-images.githubusercontent.com/12601105/67333957-b91e3000-f521-11e9-9102-8d97382ca3b9.png)
