### ISSUE TITLE
App doesn't match screen size on tablets (Galaxy Tab S3)

### ISSUE THREAD

**Issue by RipperDrone** [ImmersionRC/LapRFTimingAndroidPublic#2]
Here's a snapshot, app doesn't scale well on tablets, it cuts off vital part of the screen:

[https://photos.app.goo.gl/2Y5UN9AgMvCV9tka7](url)

**Comment by tonycake** [comment]
This should be fixed in "Clean up layouts to fix compatibility with various tablets"
